import 'risk_notice.dart';

/// The question the server wants asked next.
///
/// Strings rather than an enum: the flow is decided server-side, and a build
/// that meets a step it does not know must fall through to "nothing left to
/// ask" instead of crashing.
abstract final class OnboardingStep {
  static const birthDate = 'birth_date';
  static const practitionerType = 'practitioner_type';
  static const experience = 'experience';
  static const instructorCertificate = 'instructor_certificate';
  static const experienceQuiz = 'experience_quiz';
  static const done = 'done';
}

/// A choice, labelled by the server so the app never hardcodes the wording.
class OnboardingOption {
  const OnboardingOption({required this.value, required this.label});

  final String value;
  final String label;

  factory OnboardingOption.fromJson(Map<String, dynamic> json) =>
      OnboardingOption(
        value: json['value'] as String,
        label: json['label'] as String,
      );
}

class OnboardingState {
  const OnboardingState({
    required this.nextStep,
    required this.completed,
    this.practitionerOptions = const [],
    this.experienceOptions = const [],
    this.pendingDocuments = const [],
  });

  final String nextStep;
  final bool completed;
  final List<OnboardingOption> practitionerOptions;
  final List<OnboardingOption> experienceOptions;
  final List<RiskNotice> pendingDocuments;

  factory OnboardingState.fromJson(Map<String, dynamic> json) => OnboardingState(
        nextStep: json['next_step'] as String? ?? OnboardingStep.done,
        completed: json['completed'] as bool? ?? false,
        practitionerOptions: _options(json['practitioner_options']),
        experienceOptions: _options(json['experience_options']),
        pendingDocuments: (json['pending_documents'] as List<dynamic>? ?? const [])
            .map((d) => RiskNotice.fromJson(d as Map<String, dynamic>))
            .toList(growable: false),
      );

  static List<OnboardingOption> _options(dynamic raw) =>
      (raw as List<dynamic>? ?? const [])
          .map((o) => OnboardingOption.fromJson(o as Map<String, dynamic>))
          .toList(growable: false);
}

/// An account, as the app knows it after signing in.
class AppSession {
  const AppSession({
    required this.accessToken,
    required this.refreshToken,
    required this.displayName,
    required this.isGuest,
    this.guestKey,
    this.nextStep = OnboardingStep.birthDate,
  });

  final String accessToken;
  final String refreshToken;

  /// Generated by the server for guests; chosen (or derived) otherwise.
  final String displayName;
  final bool isGuest;

  /// Returned **once**, when an anonymous account is created. Never again.
  final String? guestKey;

  final String nextStep;

  factory AppSession.guestFromJson(Map<String, dynamic> json) {
    final tokens = json['tokens'] as Map<String, dynamic>;
    return AppSession(
      accessToken: tokens['access_token'] as String,
      refreshToken: tokens['refresh_token'] as String,
      displayName: json['display_name'] as String,
      isGuest: true,
      guestKey: json['guest_key'] as String?,
      nextStep: json['next_step'] as String? ?? OnboardingStep.birthDate,
    );
  }
}

// --- the vault game ---------------------------------------------------------

class QuizQuestion {
  const QuizQuestion({
    required this.index,
    required this.clue,
    required this.options,
    this.mediaUrl,
  });

  final int index;
  final String clue;
  final List<String> options;
  final String? mediaUrl;

  factory QuizQuestion.fromJson(Map<String, dynamic> json) => QuizQuestion(
        index: json['index'] as int,
        clue: json['clue'] as String,
        mediaUrl: json['media_url'] as String?,
        options: (json['options'] as List<dynamic>)
            .map((o) => o as String)
            .toList(growable: false),
      );
}

class Quiz {
  const Quiz({
    required this.attemptId,
    required this.title,
    required this.intro,
    required this.questions,
  });

  final String attemptId;
  final String title;
  final String intro;
  final List<QuizQuestion> questions;

  factory Quiz.fromJson(Map<String, dynamic> json) => Quiz(
        attemptId: json['attempt_id'] as String,
        title: json['title'] as String,
        intro: json['intro'] as String? ?? '',
        questions: (json['questions'] as List<dynamic>)
            .map((q) => QuizQuestion.fromJson(q as Map<String, dynamic>))
            .toList(growable: false),
      );
}

class QuizCorrection {
  const QuizCorrection({
    required this.correctAnswer,
    required this.isCorrect,
    this.givenAnswer,
  });

  final String correctAnswer;
  final bool isCorrect;
  final String? givenAnswer;

  factory QuizCorrection.fromJson(Map<String, dynamic> json) => QuizCorrection(
        correctAnswer: json['correct_answer'] as String,
        isCorrect: json['is_correct'] as bool,
        givenAnswer: json['given_answer'] as String?,
      );
}

class QuizResult {
  const QuizResult({
    required this.score,
    required this.total,
    required this.passed,
    required this.message,
    required this.corrections,
    this.countsTowardsLevel = true,
  });

  final int score;
  final int total;
  final bool passed;
  final String message;
  final List<QuizCorrection> corrections;

  /// False on every run after the first.
  ///
  /// The starting level is settled by the first completed run and never moves
  /// again — otherwise the game would be a lockpick: fail on purpose, read the
  /// answers off the correction screen, play again. Later runs still happen,
  /// they are just played for their own sake.
  final bool countsTowardsLevel;

  factory QuizResult.fromJson(Map<String, dynamic> json) => QuizResult(
        score: json['score'] as int,
        total: json['total'] as int,
        passed: json['passed'] as bool,
        message: json['message'] as String? ?? '',
        countsTowardsLevel: json['counts_towards_level'] as bool? ?? true,
        corrections: (json['corrections'] as List<dynamic>? ?? const [])
            .map((c) => QuizCorrection.fromJson(c as Map<String, dynamic>))
            .toList(growable: false),
      );
}
