import 'package:flutter_map_vector_tiles/flutter_map_vector_tiles.dart' as vt;

/// Loads the "ricamo" (embroidery) map style: the world drawn as stitching on
/// linen — the same style the web app has always used.
///
/// The style document lives in `assets/map/embroidery_style.json`, generated by
/// `scripts/build_embroidery_style.py` from `scripts/pk_embroidery_style.py`,
/// the single source shared with the web bundle. Its vector tiles come from
/// OpenFreeMap (OpenMapTiles schema, no API key).
class MapStyleLoader {
  const MapStyleLoader();

  /// `asset://` URI of the style bundled with the app.
  static const String styleUri = 'asset://assets/map/embroidery_style.json';

  /// Reads and parses the style. Callers own the result and must
  /// [vt.Style.dispose] it.
  Future<vt.Style> load() => vt.StyleReader(uri: styleUri).read();
}
